FROM neo4j:latest

WORKDIR /usr/src/neo4j

#COPY ./dump/neo4j.dump /var/lib/neo4j/dumps/neo4j.dump
#RUN neo4j-admin load --verbose --force --database=neo4j --from=/var/lib/neo4j/dumps/neo4j.dump
COPY ./dump/neo4j.dump /tmp/neo4j.dump
RUN neo4j-admin load --verbose --force --database=neo4j --from=/tmp/neo4j.dump

EXPOSE 7474
EXPOSE 7687
