FROM node:16

WORKDIR /usr/src/site

ENV NODE_ENV=production
ENV PORT=5000

COPY package*.json ./

#RUN npm install --production
RUN npm ci --only=production
RUN npm install pm2 -g

COPY . .

EXPOSE 5000

CMD ["pm2-runtime", "alzkb.js"]
