FROM node:16

# Create app directory
WORKDIR /usr/src/app

ENV NODE_ENV=production
ENV PORT=5000

# Install app dependencies
# Copy both package.json and package-lock.json
COPY package*.json ./

RUN npm ci --only=production
RUN npm install pm2 --location=global
# if building code for production

# Bundle app source
COPY . .

EXPOSE 5000
CMD ["pm2-runtime", "alzkb.js"]
